### ISSUE TITLE
Server-side master implementation

### ISSUE THREAD

**Issue by hero101** [alkem-io/whiteboard-collaboration-service#22]
## Description

As a <persona or stakeholder type>
I want <some software feature>
So that <some business value>

## Acceptance criteria

- [x] There is a master copy on the server (snapshot)
- [x] The snapshot represents the latest state in the collaboration session
- [x] The snapshot is saved to the database every `X_FROM_CONFIG` seconds
- [x] The snapshot is used to initialize every newly connected client
- [x] The client does not save
- [x] The server does not send save requests

**Comment by Comoque1** [comment]
Tested OK on sandbox env.
