### ISSUE TITLE
BUG: Last saved on whiteboards does not work

### ISSUE THREAD

**Issue by hero101** [alkem-io/whiteboard-collaboration-service#8]
**Describe the bug**
Since the handling of whiteboards has been moved to a separate microservice, the "last saved" indicator has stopped working.

**To Reproduce**
1. Go to a whiteboard
2. Wait for a save or save manually
3. The "last saved" message on the bottom left has not changed.

**Expected behavior**
The 'last saved' indicator correctly displays the time since the last save.

**Comment by Comoque1** [comment]
Tested OK on dev env.
